# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('convener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_convened', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(max_length=18)),
                ('level', models.IntegerField(max_length=2)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.ModuleDefinition'),
        ),
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='modules_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
