# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledefinition',
            name='credits',
            field=models.IntegerField(max_length=3),
        ),
    ]
