# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20171221_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('code', models.CharField(max_length=7)),
                ('credits', models.IntegerField(max_length=18)),
                ('time', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='convener',
        ),
        migrations.RemoveField(
            model_name='module',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='module',
            name='students',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModuleDefinition',
        ),
    ]
